apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    release: gamedeployment
  name: gamedeployments.tkex.tencent.com
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.replicas
      description: The desired number of pods.
      name: DESIRED
      type: integer
    - JSONPath: .status.updatedReplicas
      description: The number of pods updated.
      name: UPDATED
      type: integer
    - JSONPath: .status.updatedReadyReplicas
      description: The number of pods updated and ready.
      name: UPDATED_READY
      type: integer
    - JSONPath: .status.readyReplicas
      description: The number of pods ready.
      name: READY
      type: integer
    - JSONPath: .status.replicas
      description: The number of currently all pods.
      name: TOTAL
      type: integer
    - JSONPath: .metadata.creationTimestamp
      description: CreationTimestamp is a timestamp representing the server time when
        this object was created. It is not guaranteed to be set in happens-before order
        across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC.
      name: AGE
      type: date
  group: tkex.tencent.com
  names:
    kind: GameDeployment
    listKind: GameDeploymentList
    plural: gamedeployments
    singular: gamedeployment
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
      labelSelectorPath: .status.labelSelector