apiVersion: v1
kind: ConfigMap
metadata:
  name: bscp-datamanager-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: bscp-datamanager-config
data:
  server.yaml: |-
    server:
      servicename: bk-bscp-datamanager
      endpoint:
        ip: 0.0.0.0
        port: 9510
      metadata: bk-bscp-datamanager

    etcdCluster:
{{ toYaml $.Values.global.etcdCluster | indent 6 }}

    database:
{{ toYaml $.Values.global.database | indent 6 }}

    logger:
{{ toYaml $.Values.global.logger | indent 6 }}
    