apiVersion: v1
kind: ConfigMap
metadata:
  name: bscp-connserver-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: bscp-connserver-config
data:
  server.yaml: |-
    server:
      servicename: bk-bscp-connserver
      endpoint:
        ip: 0.0.0.0
        port: 9510
      metadata: bk-bscp-connserver

    etcdCluster:
{{ toYaml $.Values.global.etcdCluster | indent 6 }}

    natsmqCluster:
{{ toYaml .Values.natsmqCluster | indent 6 }}

    datamanager:
      servicename: bk-bscp-datamanager
      calltimeout: 3s

    bcscontroller:
      servicename: bscp-bcs-controller
      calltimeout: 3s

    logger:
{{ toYaml $.Values.global.logger | indent 6 }}
    