apiVersion: v1
kind: Service
metadata:
  name: bscp-connserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: bscp-connserver
spec:
  ports:
  - port: 9510
    targetPort: 9510
    name: grpc
  selector:
    app: bscp-connserver
