apiVersion: v1
kind: Service
metadata:
  name: bscp-accessserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: bscp-accessserver
spec:
  ports:
  - port: 9510
    targetPort: 9510
    name: grpc
  selector:
    app: bscp-accessserver
