apiVersion: v1
kind: ConfigMap
metadata:
  name: bscp-integrator-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: bscp-integrator-config
data:
  server.yaml: |-
    server:
      servicename: bk-bscp-integrator
      endpoint:
        ip: 0.0.0.0
        port: 9510
      metadata: bk-bscp-integrator

    etcdCluster:
{{ toYaml $.Values.global.etcdCluster | indent 6 }}

    businessserver:
      servicename: bk-bscp-businessserver
      calltimeout: 3s

    logger:
{{ toYaml $.Values.global.logger | indent 6 }}
    