apiVersion: v1
kind: ConfigMap
metadata:
  name: bscp-bcs-controller-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: bscp-bcs-controller-config
data:
  server.yaml: |-
    server:
      servicename: bk-bscp-bcs-controller
      endpoint:
        ip: 0.0.0.0
        port: 9510
      metadata: bk-bscp-bcs-controller
    etcdCluster:
{{ toYaml $.Values.global.etcdCluster | indent 6 }}
    natsmqCluster:
{{ toYaml .Values.natsmqCluster | indent 6 }}
    datamanager:
      servicename: bk-bscp-datamanager
      calltimeout: 3s
    logger:
{{ toYaml $.Values.global.logger | indent 6 }}
    