apiVersion: apps/v1
kind: Deployment
metadata:
  name: bscp-bcs-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: bscp-bcs-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bscp-bcs-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bscp-bcs-controller
    spec:
      containers:
        - name: bscp-bcs-controller
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
          - containerPort: 9510
          - containerPort: 9100
          volumeMounts:
          - name: config
            mountPath: /bk-bscp/etc/server.yaml
            subPath: server.yaml
          {{- if .Values.env }}
          env:
            {{- range .Values.env }}
              {{- with . }}
          - name: {{ .name }}
            value: "{{ .value }}"
              {{- end}}
            {{- end}}
          {{- end}}
          resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 12 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | indent 12 }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: bscp-bcs-controller-config
          items:
          - key: server.yaml
            path: server.yaml
