- name: api
  module: bcs
  project_dir: bcs/server
  alias: bcs-service
  language: binary
  version: ${bk_bcs_version}
  version_type: ce

- name: storage
  module: bcs
  project_dir: bcs/server
  alias: bcs-service
  language: binary
  version: ${bk_bcs_version}
  version_type: ce

- name: health-master
  module: bcs
  project_dir: bcs/server
  alias: bcs-service
  language: binary
  version: ${bk_bcs_version}
  version_type: ce

- name: health-slave
  module: bcs
  project_dir: bcs/server
  alias: bcs-service
  language: binary
  version: ${bk_bcs_version}
  version_type: ce

- name: dns-service
  module: bcs
  project_dir: bcs/server
  alias: bcs-service
  language: binary
  version: ${bk_bcs_version}
  version_type: ce

- name: ops
  module: bcs
  project_dir: bcs/server
  alias: bcs-service
  language: binary
  version: ${bk_bcs_version}
  version_type: ce

