apiVersion: bkbcs.tencent.com/v2
kind: AdmissionWebhookConfiguration
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: admissionwebhookconfiguration-sample
spec:
  # Add fields here
  foo: bar
