apiVersion: v1
kind: ConfigMap
metadata:
  name: bscp-templateserver-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: bscp-templateserver-config
data:
  server.yaml: |-
    server:
      servicename: bk-bscp-templateserver
      endpoint:
        ip: 0.0.0.0
        port: 9510
      metadata: bk-bscp-templateserver

    etcdCluster:
{{ toYaml $.Values.global.etcdCluster | indent 6 }}

    datamanager:
      servicename: bk-bscp-datamanager
      calltimeout: 3s

    logger:
{{ toYaml $.Values.global.logger | indent 6 }}
    