apiVersion: v1
kind: Service
metadata:
  name: bscp-templateserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: bscp-templateserver
spec:
  ports:
  - port: 9510
    targetPort: 9510
    name: grpc
  selector:
    app: bscp-templateserver
